# Generated by Django 4.2.2 on 2023-06-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='ISBN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
