# Generated by Django 4.2.2 on 2023-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookstoremodel_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoremodel',
            name='available_book',
            field=models.IntegerField(default=10),
        ),
    ]
